# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbc641f5a0c1c56a1cd93936ff57d26d86b6471299d7dcc6c4c8e0168481b41e02fef61835cda6cfc5554cc4ad3657bac514d1e469f53b7059af0d5c89f9b674
  spotify_client_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_client_secret: <%= ENV["SPOTIFY_CLIENT_SECRET"] %>
  quantone_app_id: <%= ENV["QUANTONE_APP_ID"] %>
  quanton_app_key: <%= ENV["QUANTONE_APP_KEY"] %>

test:
  secret_key_base: 7a6ce8ee4b48a1164c1382c0f7a8aafe768fdab775a3ff52c39ede5858db2e639d0d9c8a9cbcb608382c79353c718eba418dfa071ababe06625a9086d25108a3
  spotify_client_id: <%= ENV["SPOTIFY_CLIENT_ID"] %>
  spotify_client_secret: <%= ENV["SPOTIFY_CLIENT_SECRET"] %>
  quantone_app_id: <%= ENV["QUANTONE_APP_ID"] %>
  quanton_app_key: <%= ENV["QUANTONE_APP_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
